task:
  task_name: "Brain Tumor Classification"
  image_modality: "T1-weighted contrast-enhanced magnetic resonance imaging (MRI) scans of brain"
  class_names: ["Glioma Tumor", "Meningioma Tumor", "Normal Brain", "Pituitary Tumor"]
  role: "Neuroradiologist"
  concepts: null # Set to null to trigger LLM Concept Discovery

dataset:
  adapter: "btmri"
  root: "/storage/projects3/e19-fyp-out-of-domain-gen-in-cv/BTMRI/"
  name: "btmri"
  class_names: ["Glioma Tumor", "Meningioma Tumor", "Normal Brain", "Pituitary Tumor"]
  cache_dir: "/storage/projects3/e19-fyp-out-of-domain-gen-in-cv/cache/"
