task:
  task_name: "Knee Osteoarthritis Severity Classification"
  image_modality: "anteroposterior knee X-ray images"
  class_names: ["Normal", "Doubtful", "Minimal", "Moderate", "Severe"]
  role: "Expert Radiologist"
  concepts: null # Set to null to trigger LLM Concept Discovery

dataset:
  adapter: "kneexray"
  root: "/storage/projects3/e19-fyp-out-of-domain-gen-in-cv/KneeXray/"
  name: "kneexray"
  class_names: ["Normal", "Doubtful", "Minimal", "Moderate", "Severe"]
  cache_dir: "/storage/projects3/e19-fyp-out-of-domain-gen-in-cv/cache/"
